name: UPM Release
on:
  workflow_dispatch:

concurrency:
  group: upm-release
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      pages: write
      contents: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x

    - name: Install DocFX
      run: dotnet tool update -g docfx
        
    - name: Generate Documentation
      run: docfx Documentation/docfx.json

    - name: Copy PDFs
      run: |
        mkdir -p "Utils.Singleton/Packages/com.uralstech.utils.singleton/Documentation~"
        cp -f "Documentation/_site/api/APIReferenceManual.pdf" "Utils.Singleton/Packages/com.uralstech.utils.singleton/Documentation~"
        cp -f "Documentation/_site/DocSource/Documentation.pdf" "Utils.Singleton/Packages/com.uralstech.utils.singleton/Documentation~"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: 'Documentation/_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Publish Release
      uses: RageAgainstThePixel/upm-release@v2
      with:
          organization-id: ${{ secrets.UNITY_ORG_ID }}
          upm-service-account-key-id: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_ID }}
          upm-service-account-key-secret: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-json: 'Utils.Singleton/Packages/com.uralstech.utils.singleton/package.json'
          split-upm-branch: 'upm'
